ecommerce/Cart/urls.py
from django.urls import path
from .import views
app_name='Cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),

]

ecommerce/Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop',include('ecommerceapp.urls')),
    path('search_app',include('search_app.urls')),
    path('cart',include('Cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/ecommerceapp/urls.py
from django.urls import path
from ecommerceapp import views
app_name='ecommerceapp'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views. ProDetail,name='ProdcatDetail'),

    ]

ecommerce/search_app/urls.py
from .import views
from django.urls import path
app_name='search_app'

urlpatterns =[
    path('',views.SearchResult,name='SearchResult'),
]

ecommerce/Cart/models.py
from django.db import models
from ecommerceapp .models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return {}.format(self.cart_id)


class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce/ecommerceapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField()
    image=models.ImageField(upload_to='category')

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('ecommerceapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product')
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('ecommerceapp:ProdcatDetail',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/Cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from .models import Cart,CartItem

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart


def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('Cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def  cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('Cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('Cart:cart_detail')

ecommerce/ecommerceapp/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})

def ProDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce/search_app/views.py
from django.shortcuts import render
from ecommerceapp.models import Product
from django.db.models import Q

# Create your views here.

def SearchResult(request):
    products=None
    query=None

    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains =query) | Q(description__contains=query))

    return render(request,'search.html',{'query':query,'products':products})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Rubik+Distressed&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script><script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   This is the cart page.
proceed to review your items and place the order
{% endblock %}
{% block title %}
Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart is empty</h1><br>
        <p class="text-center">Please click<a href="{% url 'ecommerceapp:allProdCat' %}">Here</a> To Continue Shopping</p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart</h1>
        <br>


    </div>
    <div class="row mx_auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_head">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.grt_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom-image" style="width:100px;height:100px;"> </a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}<br>
                        SKU: {{cart_item.product.id}}<br>
                        Price: $ {{cart_item.product.price}}<br>
                        Quantity: {{cart_item.quantity}} * $ {{cart_item}}<br>
                    </td>
                    <td>
                        {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'Cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon" ></i></a>
                        &nbsp;<a href="{% url 'Cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'Cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'Cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'Cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}

                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>Checkout</th>
                </tr>

                </thead>
                <tbody>
                <tr>
                    <td>
                        Please review your shopping cart item before proceeding with the order payment
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your Total is: <strong>{{total}}</strong>

                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-black my_custom_button">Continue Shopping</a>

            </div>
            {% endif %}
        </div>
    </div>

</div>

{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
  {{category.description | truncatewords:155 }}
{% else %}
  Welcome to E-shoppy
{% endif %}
{% endblock %}

{% block title %}
{% if category %}
  {{category.name}}-E-shppy
{% else %}
  See our new collection- E-shoppy
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
  <div class="row my_row_class">
    <div class="mx-auto">
    <P><a href="% url 'ecommerceapp':allProdCat'%}">Our Product Collection</a></P>
    </div>
    </div>

</div>
{% endif %}
<div class="mx-auto" >
  {% if category %}
  <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">

</div>
<br>
<div>
  <h1 class="text-center my_title">{{category.name}}</h1>
  <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
  <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products"  width="1290px" height="100px">
</div>
<br>
<div>
  <h1 class="text-center my_title">Our Product Collections</h1>
  <p class="text-justify">The Best Quotes About Life If you look at what you don't have in life, you'll never have enough.” “You only live once, but if you do it right, once is enough.” </p>
</div>
{% endif %}
<div class="container">
  <div class="row mx-auto">
    {% for product in products.object_list %}
    <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4 mt-4">
      <div class="card text-center" style="width:18rem; height:100%">
        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
        <div class="card-body">
          <h4>{{product.name}}</h4>
          <p>{{product.price}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="mx-auto">
    {% if products.paginator.num_pages > 1 %}
    <hr>
    <div class="text-center">
      {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
      {% endfor %}

    </div>
    {% endif %}


  </div>
  <br>
</div>
{% endblock %}

ecommerce/templates/footer.html
<div class="container  fixed-bottom footer my_footer">
  <p class="text-center" >@copy:ABC pvt ltd.All rights reserved</p>
</div>

ecommerce/templates/header.html
{% load static %}
<header>
  <center>
  <a href="{% url 'ecommerceapp:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logo image" width="130px"; height="130px">
  </a>
  </center>
</header>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown {% if 'ecommerceapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All products</a>
          {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Cart:cart_detail' %}"><i class="fa fa-cart-arrow-down">{{item_count}}</i></a>
      </li>
      {% endif %}
    </ul>
    <form action="{% url 'search_app:SearchResult' %}" class="form-inline my-2 my-lg-0" class="d-flex" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>


    </form>
  </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{{product.description | truncatewords:155}}
{% endblock %}
{% block title %}
{% if product %}
  {{product.name}}-ESHOPPY
{% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
  <div class="mx-auto">
    <p><a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
  </div>
</div>
<div class="container">
<br>
<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <div style="min_width:18rem;">
      <img src="{{product.image.url}}" alt="{{product.name}}">

    </div>
  </div>
  <div class="col-12 col-sm12 col-md-12 col-lg-6">
  <h1 class="my_prod_title">{{product.name}}</h1>
  <p>$ {{product.price}}</p>
  <p class="text-justify my_prod_text">{{product.description}}</p>

  {% if product.stock <= 0 %}
    <p><b>Out of stock</b></p>
  {% else %}
    <a class="btn btn-secondary" href="{% url 'Cart:add_cart' product.id %}">Add to Cart</a>
  {% endif %}
</div>
</div>
  </div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
We have variety of products
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
  <p class="text-center my_search_text">You have searched for : <b>"{{query}}"</b></p>
</div>
<div class="container">
  <div class="row mx-auto">
    {% for product in products %}
    <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4 mt-4">
      <div class="card text-center" style="width:18rem; height:100%">
        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
        <div class="card-body">
          <h4>{{product.name}}</h4>
          <p>{{product.price}}</p>
        </div>
      </div>
    </div>

  {% empty %}
  <div class="row mx-auto">
    <p class="text-center my_search_text">0 results found</p>

  </div>
    {% endfor %}
  </div>
</div>
{% endblock %}